/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CenyRouteImport } from './routes/ceny'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OkoliRouteImport } from './routes/okoli'
import { Route as PrijezdRouteImport } from './routes/prijezd'
import { Route as TrasyRouteImport } from './routes/trasy'
import { Route as UbytovaniRouteImport } from './routes/ubytovani'
import { Route as VybaveniRouteImport } from './routes/vybaveni'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OkoliRoute = OkoliRouteImport.update({
  id: '/okoli',
  path: '/okoli',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijezdRoute = PrijezdRouteImport.update({
  id: '/prijezd',
  path: '/prijezd',
  getParentRoute: () => rootRouteImport,
} as any)
const TrasyRoute = TrasyRouteImport.update({
  id: '/trasy',
  path: '/trasy',
  getParentRoute: () => rootRouteImport,
} as any)
const UbytovaniRoute = UbytovaniRouteImport.update({
  id: '/ubytovani',
  path: '/ubytovani',
  getParentRoute: () => rootRouteImport,
} as any)
const VybaveniRoute = VybaveniRouteImport.update({
  id: '/vybaveni',
  path: '/vybaveni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kontakt': typeof KontaktRoute
  '/okoli': typeof OkoliRoute
  '/prijezd': typeof PrijezdRoute
  '/trasy': typeof TrasyRoute
  '/ubytovani': typeof UbytovaniRoute
  '/vybaveni': typeof VybaveniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kontakt': typeof KontaktRoute
  '/okoli': typeof OkoliRoute
  '/prijezd': typeof PrijezdRoute
  '/trasy': typeof TrasyRoute
  '/ubytovani': typeof UbytovaniRoute
  '/vybaveni': typeof VybaveniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kontakt': typeof KontaktRoute
  '/okoli': typeof OkoliRoute
  '/prijezd': typeof PrijezdRoute
  '/trasy': typeof TrasyRoute
  '/ubytovani': typeof UbytovaniRoute
  '/vybaveni': typeof VybaveniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ceny'
    | '/kontakt'
    | '/okoli'
    | '/prijezd'
    | '/trasy'
    | '/ubytovani'
    | '/vybaveni'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ceny'
    | '/kontakt'
    | '/okoli'
    | '/prijezd'
    | '/trasy'
    | '/ubytovani'
    | '/vybaveni'
  id:
    | '__root__'
    | '/'
    | '/ceny'
    | '/kontakt'
    | '/okoli'
    | '/prijezd'
    | '/trasy'
    | '/ubytovani'
    | '/vybaveni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenyRoute: typeof CenyRoute
  KontaktRoute: typeof KontaktRoute
  OkoliRoute: typeof OkoliRoute
  PrijezdRoute: typeof PrijezdRoute
  TrasyRoute: typeof TrasyRoute
  UbytovaniRoute: typeof UbytovaniRoute
  VybaveniRoute: typeof VybaveniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okoli': {
      id: '/okoli'
      path: '/okoli'
      fullPath: '/okoli'
      preLoaderRoute: typeof OkoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijezd': {
      id: '/prijezd'
      path: '/prijezd'
      fullPath: '/prijezd'
      preLoaderRoute: typeof PrijezdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trasy': {
      id: '/trasy'
      path: '/trasy'
      fullPath: '/trasy'
      preLoaderRoute: typeof TrasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubytovani': {
      id: '/ubytovani'
      path: '/ubytovani'
      fullPath: '/ubytovani'
      preLoaderRoute: typeof UbytovaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vybaveni': {
      id: '/vybaveni'
      path: '/vybaveni'
      fullPath: '/vybaveni'
      preLoaderRoute: typeof VybaveniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenyRoute: CenyRoute,
  KontaktRoute: KontaktRoute,
  OkoliRoute: OkoliRoute,
  PrijezdRoute: PrijezdRoute,
  TrasyRoute: TrasyRoute,
  UbytovaniRoute: UbytovaniRoute,
  VybaveniRoute: VybaveniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
